In [ ]:
import pandas as pd
from pandas.api.types import is_string_dtype

data = pd.read_csv('adult.csv', na_values='?')

In [ ]:
data

      age         work-class  fnlwgt  ... hours-per-week  native-country  salary
0      39          State-gov   77516  ...           40.0   United-States   <=50K
1      50   Self-emp-not-inc   83311  ...           13.0   United-States   <=50K
2      38            Private  215646  ...           40.0   United-States   <=50K
3      53            Private  234721  ...           40.0   United-States   <=50K
4      28            Private  338409  ...           40.0            Cuba   <=50K
...    ..                ...     ...  ...            ...             ...     ...
38471  27            Private  257302  ...           38.0   United-States   <=50K
38472  40            Private  154374  ...           40.0   United-States    >50K
38473  58            Private  151910  ...           40.0   United-States   <=50K
38474  22            Private  201490  ...           20.0   United-States   <=50K
38475  52       Self-emp-inc  287927  ...           40.0   United-States    >50K

[38476 rows x 15 columns]

In [ ]:
from sklearn.preprocessing import Binarizer
cont_col = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
b_data = pd.DataFrame()

for col in data.columns:
  if col in cont_col:
    bin = Binarizer(threshold=data[col].mean())
    b_data[col] = bin.transform(data[[col]]).flatten()
  else:
    b_data[col] = data[col].copy()

TypeError: ignored

In [ ]:
b_data

Empty DataFrame
Columns: []
Index: []

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data = pd.get_dummies(b_data, drop_first=True)

ValueError: ignored

In [ ]:
data

       age  fnlwgt  ...  native-country_ Yugoslavia  salary_ >50K
0        1       0  ...                           0             0
1        1       0  ...                           0             0
2        0       1  ...                           0             0
3        1       1  ...                           0             0
4        0       1  ...                           0             0
...    ...     ...  ...                         ...           ...
32556    0       1  ...                           0             0
32557    1       0  ...                           0             1
32558    1       0  ...                           0             0
32559    0       1  ...                           0             0
32560    1       1  ...                           0             1

[32561 rows x 101 columns]

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(data.drop('salary_ >50K', axis=1), data['salary_ >50K'], train_size=0.85)

In [ ]:
train_y

27298    0
22227    1
22195    0
15639    0
31135    0
        ..
11517    0
2244     0
1252     0
10993    0
11862    0
Name: salary_ >50K, Length: 27676, dtype: uint8

In [ ]:
Log_Reg = LogisticRegression()
Log_Reg.fit(train_x, train_y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
from sklearn.metrics import accuracy_score, f1_score

acc = Log_Reg.predict(test_x)

In [ ]:
acc1 = accuracy_score(test_y, acc)
f11 = f1_score(test_y, acc)

In [ ]:
print(acc1, f11)

0.8462640736949847 0.6359670382937469